ray_altitude_range: [-2, 51]     
# [-90, 20] #6
# -60  10      Ray altitude range in [-1, 1] space: [tensor(0.2126, dtype=torch.float64), tensor(0.6346, dtype=torch.float64)]
#  应该在0.26-0.58间

num_instance_classes: 100
network_type: gpnerf_nr3d
use_scaling: False
sampling_mesh_guidance: True
separate_semantic: True
num_layers_semantic_hidden: 3
semantic_layer_dim: 128
balance_weight: True
num_semantic_classes: 5

label_name: 1018_ml_fusion_0.3
log2_hashmap_size: 22
desired_resolution: 8192
sdf_as_gpnerf: True
wgt_sem_loss: 1

